napi.post("/user").form({"userId": "testa", "email": "testa@test.com"})
napi.post("/user").form({"userId": "testb", "email": "testb@test.com"})
napi.post("/user").form({"userId": "teste", "email": "teste@test.com"})
napi.post("/user").form({"userId": "testf", "email": "testf@test.com"})
napi.delete("/user/testb")
napi.get("/user/testa")
