version: '1.0'
stages:
  - clone
  - prepare
  - pre-deploy
  - deploy
  - post-deploy
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "rajpextr/serverless-CI-CD-test"
    revision: "${{CF_BRANCH}}"
    stage: "clone"

  setup:
    image: alpine:3.7
    working_directory: ${{main_clone}}
    stage: prepare
    title: generate GCP shared credentials file
    commands:
      - mkdir -p .gcloud
      - echo -n $GCP_CREDENTIALS_FILE | base64 -d > ${PWD}/.gcloud/keyfile.json
      - cf_export GCP_SHARED_CREDENTIALS_FILE=${PWD}/.gcloud/keyfile.json
      - ls ${PWD}/.gcloud/
      - cat ${PWD}/.gcloud/keyfile.json

  lint:
    image: nikolaik/python-nodejs:latest
    title: lint
    stage: pre-deploy
    working_directory: ${{main_clone}}/ts-sandbox/functions
    commands:
      - npm install package.json
      - npm install -g typescript
      - npm run lint
      
  build:
    image: nikolaik/python-nodejs:latest
    title: build
    stage: pre-deploy
    working_directory: ${{main_clone}}/ts-sandbox/functions
    commands:
      - npm run build

  unitTest:
    image: nikolaik/python-nodejs:latest
    title: Unit Test using firebase cloud shell
    stage: pre-deploy
    working_directory: ${{main_clone}}/ts-sandbox
    commands:
      - npm install -g firebase-tools@6.8.0
      - firebase use --add saas-cloud-prototype 
      - pip install -r requirements.txt
      - python tests/curl.py
      - echo $CF_UNIT_TEST_STATUS
      
  deploy:
    #image: codefresh/serverless:1.28
    image: nikolaik/python-nodejs:latest
    stage: deploy
    title: deploy to GCP with serverless framework
    working_directory: ${{main_clone}}/ts-sandbox/functions
    commands:
      - pwd
      - ls ../../.gcloud
      #- npm install serverless-google-cloudfunctions
      - firebase deploy
    when:
      condition:
        all:
          checkUnitTestPass: '"${{CF_UNIT_TEST_STATUS}}" == "SUCCESS"'
              
  package:
    image: codefresh/serverless:1.28
    stage: post-deploy
    title: package serverless service
    working_directory: ${{main_clone}}/ts-sandbox/functions
    commands:
      - echo "Tag and push package to Cloud Storage from .serverless folder"
    when:
      condition:
         all:
           checkUnitTestPass: '"${{CF_UNIT_TEST_STATUS}}" == "SUCCESS"'
